from typing import List, Dict, Any, Optional

class HintLevel:
    INDEPENDENT = 0
    DIRECTIONAL = 1
    CONCEPT_REMINDER = 2
    GUIDED_STEP = 3
    WORKED_EXAMPLE = 4
    SIMPLER_PROBLEM = 5
    INDEPENDENT_REASSESSMENT = 6

class HintService:
    @staticmethod
    def get_hint_for_level(level: int, question: Dict[str, Any], concept: Dict[str, Any]) -> Dict[str, Any]:
        """
        Returns a hint based on the requested level.
        In a real system, these would be generated by AI or retrieved from a curated bank.
        """
        hints = question.get("hints", [])

        # Fallback logic if specific levels are missing
        if level == HintLevel.DIRECTIONAL:
            return {"text": hints[0] if hints else "Try thinking about the main goal of the question.", "level": level}

        if level == HintLevel.CONCEPT_REMINDER:
            return {
                "text": f"Remember: {concept.get('conceptName', 'this concept')} is about {concept.get('shortDescription', 'the current topic')}.",
                "level": level
            }

        if level == HintLevel.GUIDED_STEP:
            return {"text": "Step 1: Look at the given values. What do they tell you?", "level": level}

        if level == HintLevel.WORKED_EXAMPLE:
            example = concept.get("examples", [{}])[0]
            return {
                "text": "Here is a similar problem solved:",
                "example": example.get("text", "No example available."),
                "level": level
            }

        return {"text": "Let's try a different approach.", "level": level}

    @staticmethod
    def escalate_hint(current_level: int, attempt_count: int) -> int:
        """Determines the next hint level based on history."""
        if attempt_count == 1: return HintLevel.DIRECTIONAL
        if attempt_count == 2: return HintLevel.CONCEPT_REMINDER
        return min(HintLevel.INDEPENDENT_REASSESSMENT, current_level + 1)
